### ISSUE TITLE
Failure to load data in Github Application

### ISSUE THREAD

**Issue by jpvajda** [newrelic/nr1-github#62]
Filed on behalf of a user from a JIRA bug logged via the  NR1 platform feedback widget.

### Issue

I seem to have been able to make it past the GitHub app configuration (by refreshing on the prior error page I got), but now when I select "GitHub Repo" from the more views section in the left nav, I get a flash of content that's rapidly replaced with "Oops! Something went wrong."

### expected 

my linked Github repo data loads in the application

**Comment by jpvajda** [comment]
Another bit of feedback from the user: I just went through the flow to set up the GitHub integration (via the "add app" functionality. The flow is *extremely* unintuitive. I still managed to make it through to the end, only to be show "404 - Nerdlet "[guid].github" not found

**Comment by brent-yearone** [comment]
I can't provide more details on the steps to repro, because the UI doesn't let me do it again! It's now stuck with the broken integration. I can't turn it off to try re-configuring. Here's the app in question: https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJhcG0tbmVyZGxldHMub3ZlcnZpZXciLCJlbnRpdHlJZCI6Ik16RXdNRE00Tm54QlVFMThRVkJRVEVsRFFWUkpUMDU4TVRRM01UQTBPREU0TlEifQ==&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNekV3TURNNE5ueEJVRTE4UVZCUVRFbERRVlJKVDA1OE1UUTNNVEEwT0RFNE5RIiwic2VsZWN0ZWROZXJkbGV0Ijp7Im5lcmRsZXRJZCI6ImFwbS1uZXJkbGV0cy5vdmVydmlldyJ9fQ==&platform[accountId]=3100386&platform[timeRange][duration]=1800000

And I'm attaching a screen cap of what happens.

https://user-images.githubusercontent.com/78820602/111805172-08d76700-888e-11eb-98c6-a0c17ae80722.mov

**Comment by jpvajda** [comment]
@brent-yearone Thanks for the additional details here. Our team is taking a look at this problem you reported.

**Comment by jpvajda** [comment]
Updated the app via the catalog manager: https://github.com/newrelic/nr1-github/commit/86eb78c37b24b239f7c31b1d373c0859271ccda9

**Comment by brent-yearone** [comment]
This is better, but the integration is still broken. I'm not sure exactly why. I've attached another screencast so you can see what's going on.

The weird thing is that the repo's page doesn't load on the first try in Github, but just going into the browser address bar and hitting enter makes it work. :shrug:

[Screen Recording 2021-03-24 at 8.26.05 AM.mov.zip](https://github.com/newrelic/nr1-github/files/6198382/Screen.Recording.2021-03-24.at.8.26.05.AM.mov.zip)

**Comment by jpvajda** [comment]
Thanks @brent-yearone we'll continue to take a look at this issue.

**Comment by LizBaker** [comment]
hey @brent-yearone, can you check the permissions on the github token you're using? i was able to recreate the errors on contributors and PRs by using a token with only public access. once i tried a token with repo access it was successful. the missing readme and wonky link are still questionable but maybe we can make some progress with the token permissions first

**Comment by brent-yearone** [comment]
@LizBaker that did the trick! Thank you! Some better messaging on those errors in the UI might be nice -- especially since the fix on my end is so quick & easy. :)

**Comment by LizBaker** [comment]
@brent-yearone absolutely! I'll update the UI
